plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRailsVersion: 6.1
  Exclude:
    - bin/bundle
    - db/schema.rb
    - tmp/**/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
