x-app-service: &app-service
  build: .
  image: "books.mtdr-dev:latest"
  volumes:
    - .:/app
    - ./tmp/bundle:/usr/local/bundle
    - ~/.gitconfig:/root/.gitconfig

services:
  shell:
    <<: *app-service
    command: bash
    stdin_open: true
    tty: true
    depends_on: []
    profiles:
      - shell

  web:
    <<: *app-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - "3010:3000"
    depends_on:
      - webpacker
    stdin_open: true
    tty: true
    profiles:
      - admin
      - web

  webpacker:
    <<: *app-service
    command: bash -c "rm -rf /app/public/packs; /app/bin/webpack-dev-server"
    ports:
      - "3035:3035"
    profiles:
      - admin
      - tools
      - web

volumes:
  data:
