name: ESLint + Stylelint
on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-linters-front-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch base for diff
        run: git fetch origin

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Yarn setup
        run: |
          yarn install --frozen-lockfile

      - name: Run Stylelint
        run: yarn run stylelint "app/assets/stylesheets/**/*.{css,scss}"

      - name: Run ESLint
        run: yarn run eslint "app/javascript/admin/**/*.{js,jsx}" --max-warnings 0
