name: Backend linters & safety checks
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - rubo-push

concurrency:
  group: ci-linters-back-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analize:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: development
    steps:
      - uses: actions/checkout@v4

      - name: Fetch base for diff
        run: git fetch origin

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Pronto
        if: github.event_name == 'pull_request'
        run: bundle exec pronto run -f github_status github_pr_review -c origin/${{ github.base_ref }}
        env:
          PRONTO_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          PRONTO_GITHUB_ACCESS_TOKEN: "${{ github.token }}"

      - name: Run Rubocop
        if: github.event_name == 'push'
        run: bundle exec rubocop -c ./.rubocop.yml

      - name: Run Bundle Audit
        run: bundle exec bundler-audit check --update
