name: ESLint + Stylelint
on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-linters-front-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch base for diff
        run: git fetch origin

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Yarn setup
        run: |
          yarn install --frozen-lockfile
          yarn add --dev @babel/core @babel/eslint-parser @babel/preset-react @babel/preset-env \
            @babel/plugin-syntax-dynamic-import \
            @babel/plugin-transform-destructuring \
            @babel/plugin-transform-class-properties \
            @babel/plugin-proposal-private-methods \
            @babel/plugin-transform-object-rest-spread \
            @babel/plugin-transform-runtime \
            @babel/plugin-transform-regenerator

      - name: Run ESLint
        run: yarn run eslint "app/javascript/**/*.{js,jsx}" --max-warnings 0

      - name: Run Stylelint
        run: yarn run stylelint "app/assets/stylesheets/**/*.{css,scss}"
