name: Rubocop
on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-linters-back-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analize:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Fetch base for diff
        run: git fetch origin

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup pronto and rubocop
        run: |
          gem install rugged:1.6.5
          gem install pronto pronto-rubocop
          gem install rubocop rubocop-rails rubocop-rspec rubocop-performance

      - name: Run Pronto
        run: pronto run -f github_status github_pr_review -c origin/${{ github.base_ref }}
        env:
          PRONTO_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          PRONTO_GITHUB_ACCESS_TOKEN: "${{ github.token }}"
